spring:
  application:
    name: manager

  datasource:
    main:
      url: jdbc:h2:mem:task_db;DB_CLOSE_DELAY=-1;
      driver-class-name: org.h2.Driver
      username: sa
      password: password
    backup:
      url: jdbc:postgresql://localhost:5332/task_db
      driver-class-name: org.postgresql.Driver
      username: test
      password: test

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: task-created
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


